Xero.Api.Example.MVC/Controllers/HomeController.cs
using System.Web.Mvc;
using Xero.Api.Example.Applications.Public;
using Xero.Api.Example.MVC.Helpers;
using Xero.Api.Infrastructure.OAuth;

namespace Xero.Api.Example.MVC
{
    public class HomeController : Controller
    {
        private IMvcAuthenticator _authenticator;
        private ApiUser _user;

        public HomeController()
        {
            _user = XeroApiHelper.User();

            _authenticator = XeroApiHelper.MvcAuthenticator();
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Connect()
        {
            var authorizeUrl = _authenticator.GetRequestTokenAuthorizeUrl(_user.Name);

            return Redirect(authorizeUrl);
        }

        public ActionResult Authorize(string oauth_token, string oauth_verifier, string org)
        {          
            var accessToken = _authenticator.RetrieveAndStoreAccessToken(_user.Name, oauth_token, oauth_verifier, org);
            if (accessToken == null)
                return View("NoAuthorized");            

            return View(accessToken);
        }
    }
}

Xero.Api.Example.MVC/Controllers/OrganisationController.cs
using System.Web.Mvc;
using Xero.Api.Example.Applications.Public;
using Xero.Api.Example.MVC.Helpers;

namespace Xero.Api.Example.MVC.Controllers
{
    public class OrganisationController : Controller
    {
        public ActionResult Index()
        {
            var api = XeroApiHelper.CoreApi();

            //var api1 = XeroApiHelper.User();

            try
            {
                var organisation = api.Organisation;

                
                //var updated_emp = api.Update(new Employee
                //{
                //    Id = emp.Id,
                //    Status = Xero.Api.Payroll.Australia.Model.Status.EmploymentStatus.Terminated,
                //    TerminationDate = DateTime.Now.AddDays(-1)

                //});



                return View(organisation);
            }
            catch (RenewTokenException e)
            {
                return RedirectToAction("Connect", "Home");
            }   
        }
    }
}

Xero.Api.Example.MVC/Views/Home/Authorize.cshtml
@model Xero.Api.Infrastructure.Interfaces.IToken

@{
    ViewBag.Title = "Authorize";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Authorized</h2>
<h3>Token Key: @Model.TokenKey</h3>
<h3>Token Secret: @Model.TokenSecret</h3>
<h3>Expires At: @Model.ExpiresAt</h3>

@if (!string.IsNullOrEmpty(@Model.Session))
{
    <h3>Session: @Model.Session</h3>
}


@Html.ActionLink("Organisation Details", "Index", "Organisation")

Xero.Api.Example.MVC/Views/Home/Connect.cshtml
@{
    ViewBag.Title = "Connect";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Connect</h2>

Xero.Api.Example.MVC/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@Html.ActionLink("Connect to xero", "Connect", "Home", new { id = "btnConnect" })    

Xero.Api.Example.MVC/Views/Home/NoAuthorized.cshtml
@{
    ViewBag.Title = "Not Authorized";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

Xero.Api.Example.MVC/Views/Organisation/Index.cshtml
@model Xero.Api.Core.Model.Organisation

@{
    ViewBag.Title = "Organisation";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Organisation Details</h2>
<h3>Name: @Model.Name</h3>

<h3>Base Currency: @Model.BaseCurrency</h3>

Xero.Api.Example.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>

    <link href="~/Content/Site.css" rel="stylesheet" />
</head>
<body>
    @RenderBody()

    @RenderSection("scripts", required: false)
</body>
</html>